### PR TITLE
auth-screen

### PR DESCRIPTION
**Pull request by sumitk-singh**
## auth screen added, code to review in-
- auth page

### CODE REVIEW

**Review by humzahasan — APPROVED** [review]
- Code looks clean
- Like your overall structuring of folder.

Good to merge!

**Review by rutu14 — APPROVED** [review]
The code is good to merge.
In UI part, the footer is not at the end of the page.

**Review by Shubhamkr2610 — APPROVED** [review]
your code is clean and readable . nothing change recommended from my side. Looks everything good to me , You can merge it

**Review by zoyatanweer — APPROVED** [review]
- neat and understandable code
- liked your folder structure 
- good to merge

**Pull request merged**
